Chatapp
PukieDiederik/transcendence pull request #1
Opened 2023-06-13 22:23 UTC by Dmarceli

containerized backend and frontend, started with methods and channels selections

2023-06-15 13:41 UTC, PukieDiederik requested changes
Hello,
As promised I will give an explanation of why I can't accept this pull request.

First of all, let's talk about the `.env` file. You removed this from the gitignore and added it to git. A `.env` file should **NEVER** be added to git. A `.env` (otherwise known as the environment file) is used to configure the project for YOUR enviroment. Your environment might look different from mine. In this file you also usually add sensitive information (like here you added the DB_PASS which is sensitive information) which you NEVER WANT ON YOUR GIT. Removing it and commiting doesn't solve the issue (git is a list of changes, so removing your env file means its still visible in older commits). The `.env.example` file has also been deleted. This file serves to show which variables you need to/can set. Now if no .env file is present people wont easily understand how to configure our project.

Another thing, commiting to branches after creating a pull request. When you commit to your branch after having made a pull request will invalidate any review made on that branch (it is configured this way). Normally you don't need to push to the branch after a PR unless changes are requested/you needed to fix something. If you want to keep working on that feature it probably means it was not completed. If you want to continue working with those changes implemented but on another feature, you create a new branch.

What should be in a pull request? One feature. In this case it has added: the backend initial setup, the frontend initial setup, a chat app, database generation, endpoints. All of these should be seperate PR's. Now it is really hard to check everything you have done (because now I have to look through 11k+ changes instead of having the init be ~9k, and then having 3-4 other pull requests with only a couple hundred changes).

Last, the pull request message. A pull request message should give you a good overview of what has changed, why it has changed and what issues are related to a PR. It also helps if you give resources on how to test your code.

How I would like to see this PR split. First we should have 2 PRs for the initial setup of the frontend and the backend. Both of them should include a `dockerfile` and modify the `docker-compose` accordingly. After this we should have 3 seperate PRs for the database, the endpoints, and the chat app. (I don't think I need to say this but these should all be on seperate branches.) I recommend going back to the master branch (which should NOT have been modified yet) and creating new branches from there. Then you can copy over the files from this branch when you need them.

2023-06-17 15:21 UTC, PukieDiederik commented on docker-compose.yml
> +      - '5173:5173'
Might be worth changing to port 80?

2023-06-17 16:36 UTC, PukieDiederik reviewed
.

2023-06-17 16:36 UTC, PukieDiederik commented on backend/src/users/users.controller.ts
> +
[REFACTORING] The endpoints

2023-06-17 16:36 UTC, PukieDiederik commented on backend/src/chat/chat.entity.ts
Rename this module to "message"

2023-06-17 16:36 UTC, PukieDiederik commented on backend/src/chat/chat.entity.ts
> +    author: string;
Should reference a user instead of a string

2023-06-17 16:36 UTC, PukieDiederik commented on backend/src/chat/chat.entity.ts
> +    channel: number;
should reference a channel

2023-06-17 16:36 UTC, PukieDiederik commented on backend/src/game_history/game_history.entity.ts
> +    points: number;
[REFACTORING] rename to `xp`, `xp_gained` or something similar

2023-06-17 16:36 UTC, PukieDiederik commented on frontend/src/App.vue
> +const socket = io('http://localhost:3000');
recommend not hard coding this

2023-06-17 16:36 UTC, PukieDiederik commented on docker-compose.yml
> +    entrypoint: ["bash" , "-c" , "npm install && npm run dev"]
Requested changes:

- [ ] Update makefile.
- [ ] Create docker files.
- [ ] rename chat table to something like `message`
- [ ] On "chat" do not use numbers or strings and instead use the correct entity
- [ ] Move database modules to seperate folder.

2023-06-17 17:47 UTC, ncameiri commented on frontend/src/App.vue
> +const socket = io('http://localhost:3000');
To be adressed on issue #9

2023-06-17 20:58 UTC, closed without merging